config/routes.rb
Rails.application.routes.draw do

  root 'crosswords#index'

  resources :crosswords do
    collection do
      get 'autocomplete'
    end
  end

end

app/models/crossword.rb
class Crossword < ActiveRecord::Base
  searchkick word_start: [:name]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crosswords_controller.rb
class CrosswordsController < ApplicationController
  def index
    @words = Crossword.search(params[:query] || "*", fields: [:name], match: :word_start, operator: "and")
  end

  def autocomplete
    render json: Crossword.search(params[:query], {
        fields: [:name],
        match: :word_start,
        limit: 10,
        load: false,
        misspellings: {below: 3}
    }).map(&:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crosswords_helper.rb
module CrosswordsHelper
end

app/views/crosswords/index.html.erb
<style>
  .tt-input {
    box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
  }

  .tt-hint {
    color: #999;
  }

  .tt-menu {
    width: 422px;
    margin-top: 12px;
    padding: 8px 0;
    background-color: #fff;
    border: 1px solid #ccc;
    border: 1px solid rgba(0, 0, 0, 0.2);
    border-radius: 8px;
    box-shadow: 0 5px 10px rgba(0,0,0,.2);
  }

  .tt-suggestion {
    padding: 3px 20px;
    font-size: 18px;
    line-height: 24px;
  }

  .tt-suggestion.tt-cursor {
    color: #fff;
    background-color: #0097cf;
  }

  .tt-suggestion p {
    margin: 0;
  }
</style>

<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-3">Test Searchkick Integration</h1>
    <p class="lead">This is an attempt to see if searchkick will work for our needs.</p>
  </div>
</div>


<div class="container">
  <div class="row">
    <% # search form %>
    <div class="col-md-10">
      <%= form_tag autocomplete_crosswords_path, method: :get do %>
          <div class="form-group">
            <%= label_tag 'Try Finding a Word:' %>
            <%= text_field_tag "query", params[:query], class: 'form-control' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.js"
integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE="
crossorigin="anonymous"></script>
<%= javascript_include_tag "typeahead.bundle.js" %>
<script>
    var words = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        remote: {
            url: '/crosswords/autocomplete?query=%QUERY',
            wildcard: '%QUERY'
        }
    });
    $('#query').typeahead(null, {
        source: words
    });
    $('.tt-suggestion.tt-selectable').hover(function(){
        $(this).css("background-color", "yellow");
    }, function(){
        $(this).css("background-color", "pink");
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElasticSearchTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
</head>
<body>

<%= yield %>
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
</body>
</html>